# SPDX-FileCopyrightText: 2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
#
# SPDX-License-Identifier: MIT

telemetry = false
[install]
exact = true
frozenLockfile = true
minimumReleaseAge = 172800
[install.lockfile]
save = true
